config={'version': 'v1',
 'config': {'visState': {'filters': [],
   'layers': [{'id': 'gfxu0nb',
     'type': 'point',
     'config': {'dataId': 'Airbnb listings in Barcelona',
      'label': 'Point',
      'color': [248, 149, 112],
      'columns': {'lat': 'latitude', 'lng': 'longitude', 'altitude': None},
      'isVisible': True,
      'visConfig': {'radius': 10,
       'fixedRadius': False,
       'opacity': 0.88,
       'outline': False,
       'thickness': 2,
       'strokeColor': None,
       'colorRange': {'name': 'UberPool 6',
        'type': 'diverging',
        'category': 'Uber',
        'colors': ['#213E9A',
         '#551EAD',
         '#C019BD',
         '#D31256',
         '#E6470A',
         '#F9E200']},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radiusRange': [0, 50],
       'filled': True},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'review_scores_rating',
       'type': 'integer'},
      'colorScale': 'quantize',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'Airbnb listings in Barcelona': [{'name': 'id',
        'format': None},
       {'name': 'listing_url', 'format': None},
       {'name': 'scrape_id', 'format': None},
       {'name': 'last_scraped', 'format': None},
       {'name': 'name', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.409878782707835,
   'longitude': 2.155768087544948,
   'pitch': 0,
   'zoom': 11.358098278408187,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}

